version: 1
accounts:
  - name: aakash
    coins: ["200000token", "200000000stake"]
    mnemonic: play butter frown city voyage pupil rabbit wheat thrive mind skate turkey helmet thrive door either differ gate exhibit impose city swallow goat faint
  - name: tiger
    coins: ["100000token", "100000000stake"]
validators:
  - name: aakash
    bonded: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: tiger
  coins: ["5token", "100000stake"]